### ISSUE TITLE
Missing audio.config

### ISSUE THREAD

**Issue by jamesnhan** [T-Grave/goxlr-on-linux#7]
The instructions mention moving an audio.config file to /etc/security/limits.d/ from the repository, but the repository does not include this file.

**Comment by T-Grave** [comment]
@Gregory-Hepicloud can you add the file? This is part of the Arch installation steps

**Comment by Gregory-Hepicloud** [comment]
Hi, We have make pull request file is coming soon

**Comment by T-Grave** [comment]
The file has been merged in. closing this.
